CI: check if browser installed

diff --git a/.github/workflows/run_tests.yaml b/.github/workflows/run_tests.yaml
--- a/.github/workflows/run_tests.yaml
+++ b/.github/workflows/run_tests.yaml
@@ -16,33 +16,38 @@ jobs:
       checks: write
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-    - name: setup Python
-      uses: actions/setup-python@v3
-      with:
-        python-version: "3.10"
+      - name: setup Python
+        uses: actions/setup-python@v3
+        with:
+          python-version: "3.10"
 
-    - name: Install Chrome and WebDriver
-      run: |
-        brew install --cask google-chrome
+      - name: Install Chrome and WebDriver if not already installed
+        run: |
+          if ! command -v google-chrome &>/dev/null; then
+            echo "Installing Chrome"
+            brew install --cask google-chrome
+          else
+            echo "Chrome is already installed"
+          fi
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-        pip install --upgrade pytest pytest-html
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+          pip install --upgrade pytest pytest-html
 
 
-    - name: Run tests
-      run: |
-        python -m pytest --verbose --junit-xml=test-results.xml
+      - name: Run tests
+        run: |
+          python -m pytest --verbose --junit-xml=test-results.xml
 
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v3
-      if: success() || failure() # always run even if the previous step fails
-      with:
-        report_paths: '**/test-results.xml'
-        detailed_summary: true
-        include_passed: true
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/test-results.xml'
+          detailed_summary: true
+          include_passed: true
